<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2pqfBFG' shared service.

return $this->privates['.service_locator.2pqfBFG'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('accountRepo' => function (): \App\Repository\CeAccountRepository {
    return ($this->privates['App\Repository\CeAccountRepository'] ?? $this->load('getCeAccountRepositoryService.php'));
}));
