<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pJQU8et' shared service.

return $this->privates['.service_locator.pJQU8et'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('chargeRepo' => function (): \App\Repository\CeChargeRepository {
    return ($this->privates['App\Repository\CeChargeRepository'] ?? $this->load('getCeChargeRepositoryService.php'));
}, 'manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'networkRep' => function (): \App\Repository\CeNetworkRepository {
    return ($this->privates['App\Repository\CeNetworkRepository'] ?? $this->load('getCeNetworkRepositoryService.php'));
}));
