<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vtOhNkH' shared service.

return $this->privates['.service_locator.vtOhNkH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('acEntryRepo' => function (): \App\Repository\CeAccountEntryRepository {
    return ($this->privates['App\Repository\CeAccountEntryRepository'] ?? $this->load('getCeAccountEntryRepositoryService.php'));
}, 'accountRepo' => function (): \App\Repository\CeAccountRepository {
    return ($this->privates['App\Repository\CeAccountRepository'] ?? $this->load('getCeAccountRepositoryService.php'));
}, 'orderRepo' => function (): \App\Repository\CeorderRepository {
    return ($this->privates['App\Repository\CeorderRepository'] ?? $this->load('getCeorderRepositoryService.php'));
}));
