<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Q6OpND9' shared service.

return $this->privates['.service_locator.Q6OpND9'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('customerRepo' => function (): \App\Repository\CeCustomerRepository {
    return ($this->privates['App\Repository\CeCustomerRepository'] ?? $this->load('getCeCustomerRepositoryService.php'));
}, 'repo' => function (): \App\Repository\CeorderRepository {
    return ($this->privates['App\Repository\CeorderRepository'] ?? $this->load('getCeorderRepositoryService.php'));
}, 'statusRepo' => function (): \App\Repository\CeStatusRepository {
    return ($this->privates['App\Repository\CeStatusRepository'] ?? $this->load('getCeStatusRepositoryService.php'));
}, 'townRepo' => function (): \App\Repository\CeTownRepository {
    return ($this->privates['App\Repository\CeTownRepository'] ?? $this->load('getCeTownRepositoryService.php'));
}));
