<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VTkYoLV' shared service.

return $this->privates['.service_locator.VTkYoLV'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('chargeRep' => function (): \App\Repository\CeAccountRepository {
    return ($this->privates['App\Repository\CeAccountRepository'] ?? $this->load('getCeAccountRepositoryService.php'));
}, 'entryRepo' => function (): \App\Repository\CeAccountEntryRepository {
    return ($this->privates['App\Repository\CeAccountEntryRepository'] ?? $this->load('getCeAccountEntryRepositoryService.php'));
}));
