<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fAQ3KxQ' shared service.

return $this->privates['.service_locator.fAQ3KxQ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('accountTypeRepo' => function (): \App\Repository\CeAccountTypeRepository {
    return ($this->privates['App\Repository\CeAccountTypeRepository'] ?? $this->load('getCeAccountTypeRepositoryService.php'));
}, 'bankRepo' => function (): \App\Repository\CeBankRepository {
    return ($this->privates['App\Repository\CeBankRepository'] ?? $this->load('getCeBankRepositoryService.php'));
}, 'customerRepo' => function (): \App\Repository\CeCustomerRepository {
    return ($this->privates['App\Repository\CeCustomerRepository'] ?? $this->load('getCeCustomerRepositoryService.php'));
}, 'manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}));
