<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccountController::accountBuy' => function () {
    return ($this->privates['.service_locator.zHcJrVx'] ?? $this->load('get_ServiceLocator_ZHcJrVxService.php'));
}, 'App\\Controller\\AccountController::accountDeposit' => function () {
    return ($this->privates['.service_locator.9kx.pPz'] ?? $this->load('get_ServiceLocator_9kx_PPzService.php'));
}, 'App\\Controller\\AccountController::accountList' => function () {
    return ($this->privates['.service_locator.2pqfBFG'] ?? $this->load('get_ServiceLocator_2pqfBFGService.php'));
}, 'App\\Controller\\AccountController::accountReceive' => function () {
    return ($this->privates['.service_locator.fAQ3KxQ'] ?? $this->load('get_ServiceLocator_FAQ3KxQService.php'));
}, 'App\\Controller\\AccountController::accountTransfer' => function () {
    return ($this->privates['.service_locator.9kx.pPz'] ?? $this->load('get_ServiceLocator_9kx_PPzService.php'));
}, 'App\\Controller\\AccountController::ceAccountForm' => function () {
    return ($this->privates['.service_locator.9kx.pPz'] ?? $this->load('get_ServiceLocator_9kx_PPzService.php'));
}, 'App\\Controller\\AccountController::showOrder' => function () {
    return ($this->privates['.service_locator.VTkYoLV'] ?? $this->load('get_ServiceLocator_VTkYoLVService.php'));
}, 'App\\Controller\\CeorderController::abandonOrder' => function () {
    return ($this->privates['.service_locator.cGYhsd3'] ?? $this->load('get_ServiceLocator_CGYhsd3Service.php'));
}, 'App\\Controller\\CeorderController::ceorderForm' => function () {
    return ($this->privates['.service_locator.pJQU8et'] ?? $this->load('get_ServiceLocator_PJQU8etService.php'));
}, 'App\\Controller\\CeorderController::completeOrder' => function () {
    return ($this->privates['.service_locator.Fswdvxl'] ?? $this->load('get_ServiceLocator_FswdvxlService.php'));
}, 'App\\Controller\\CeorderController::deleteOrder' => function () {
    return ($this->privates['.service_locator.KVgd.iy'] ?? $this->load('get_ServiceLocator_KVgd_IyService.php'));
}, 'App\\Controller\\CeorderController::orderList' => function () {
    return ($this->privates['.service_locator.Q6OpND9'] ?? $this->load('get_ServiceLocator_Q6OpND9Service.php'));
}, 'App\\Controller\\CeorderController::ordersNew' => function () {
    return ($this->privates['.service_locator.Q6OpND9'] ?? $this->load('get_ServiceLocator_Q6OpND9Service.php'));
}, 'App\\Controller\\CeorderController::reopenOrder' => function () {
    return ($this->privates['.service_locator.cGYhsd3'] ?? $this->load('get_ServiceLocator_CGYhsd3Service.php'));
}, 'App\\Controller\\CeorderController::showOrder' => function () {
    return ($this->privates['.service_locator.WcD22Zf'] ?? $this->load('get_ServiceLocator_WcD22ZfService.php'));
}, 'App\\Controller\\CustomerController::customerForm' => function () {
    return ($this->privates['.service_locator.ivfXPti'] ?? $this->load('get_ServiceLocator_IvfXPtiService.php'));
}, 'App\\Controller\\DashboardController::index' => function () {
    return ($this->privates['.service_locator.HTCaso0'] ?? $this->load('get_ServiceLocator_HTCaso0Service.php'));
}, 'App\\Controller\\SecurityController::registrations' => function () {
    return ($this->privates['.service_locator.t7BdSgs'] ?? $this->load('get_ServiceLocator_T7BdSgsService.php'));
}, 'App\\Controller\\AccountController:accountBuy' => function () {
    return ($this->privates['.service_locator.zHcJrVx'] ?? $this->load('get_ServiceLocator_ZHcJrVxService.php'));
}, 'App\\Controller\\AccountController:accountDeposit' => function () {
    return ($this->privates['.service_locator.9kx.pPz'] ?? $this->load('get_ServiceLocator_9kx_PPzService.php'));
}, 'App\\Controller\\AccountController:accountList' => function () {
    return ($this->privates['.service_locator.2pqfBFG'] ?? $this->load('get_ServiceLocator_2pqfBFGService.php'));
}, 'App\\Controller\\AccountController:accountReceive' => function () {
    return ($this->privates['.service_locator.fAQ3KxQ'] ?? $this->load('get_ServiceLocator_FAQ3KxQService.php'));
}, 'App\\Controller\\AccountController:accountTransfer' => function () {
    return ($this->privates['.service_locator.9kx.pPz'] ?? $this->load('get_ServiceLocator_9kx_PPzService.php'));
}, 'App\\Controller\\AccountController:ceAccountForm' => function () {
    return ($this->privates['.service_locator.9kx.pPz'] ?? $this->load('get_ServiceLocator_9kx_PPzService.php'));
}, 'App\\Controller\\AccountController:showOrder' => function () {
    return ($this->privates['.service_locator.VTkYoLV'] ?? $this->load('get_ServiceLocator_VTkYoLVService.php'));
}, 'App\\Controller\\CeorderController:abandonOrder' => function () {
    return ($this->privates['.service_locator.cGYhsd3'] ?? $this->load('get_ServiceLocator_CGYhsd3Service.php'));
}, 'App\\Controller\\CeorderController:ceorderForm' => function () {
    return ($this->privates['.service_locator.pJQU8et'] ?? $this->load('get_ServiceLocator_PJQU8etService.php'));
}, 'App\\Controller\\CeorderController:completeOrder' => function () {
    return ($this->privates['.service_locator.Fswdvxl'] ?? $this->load('get_ServiceLocator_FswdvxlService.php'));
}, 'App\\Controller\\CeorderController:deleteOrder' => function () {
    return ($this->privates['.service_locator.KVgd.iy'] ?? $this->load('get_ServiceLocator_KVgd_IyService.php'));
}, 'App\\Controller\\CeorderController:orderList' => function () {
    return ($this->privates['.service_locator.Q6OpND9'] ?? $this->load('get_ServiceLocator_Q6OpND9Service.php'));
}, 'App\\Controller\\CeorderController:ordersNew' => function () {
    return ($this->privates['.service_locator.Q6OpND9'] ?? $this->load('get_ServiceLocator_Q6OpND9Service.php'));
}, 'App\\Controller\\CeorderController:reopenOrder' => function () {
    return ($this->privates['.service_locator.cGYhsd3'] ?? $this->load('get_ServiceLocator_CGYhsd3Service.php'));
}, 'App\\Controller\\CeorderController:showOrder' => function () {
    return ($this->privates['.service_locator.WcD22Zf'] ?? $this->load('get_ServiceLocator_WcD22ZfService.php'));
}, 'App\\Controller\\CustomerController:customerForm' => function () {
    return ($this->privates['.service_locator.ivfXPti'] ?? $this->load('get_ServiceLocator_IvfXPtiService.php'));
}, 'App\\Controller\\DashboardController:index' => function () {
    return ($this->privates['.service_locator.HTCaso0'] ?? $this->load('get_ServiceLocator_HTCaso0Service.php'));
}, 'App\\Controller\\SecurityController:registrations' => function () {
    return ($this->privates['.service_locator.t7BdSgs'] ?? $this->load('get_ServiceLocator_T7BdSgsService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
