<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CeNetwork extends \App\Entity\CeNetwork implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'netCode', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'netInitial', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'label', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'datec', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'ceNetwork'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'netCode', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'netInitial', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'label', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'datec', '' . "\0" . 'App\\Entity\\CeNetwork' . "\0" . 'ceNetwork'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CeNetwork $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNetCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetCode', []);

        return parent::getNetCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetCode(string $netCode): \App\Entity\CeNetwork
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetCode', [$netCode]);

        return parent::setNetCode($netCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetInitial(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetInitial', []);

        return parent::getNetInitial();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetInitial(array $netInitial): \App\Entity\CeNetwork
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetInitial', [$netInitial]);

        return parent::setNetInitial($netInitial);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel(string $label): \App\Entity\CeNetwork
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatec(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatec', []);

        return parent::getDatec();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatec(\DateTimeInterface $datec): \App\Entity\CeNetwork
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatec', [$datec]);

        return parent::setDatec($datec);
    }

    /**
     * {@inheritDoc}
     */
    public function getCeNetwork(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCeNetwork', []);

        return parent::getCeNetwork();
    }

    /**
     * {@inheritDoc}
     */
    public function addCeNetwork(\App\Entity\Ceorder $ceNetwork): \App\Entity\CeNetwork
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCeNetwork', [$ceNetwork]);

        return parent::addCeNetwork($ceNetwork);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCeNetwork(\App\Entity\Ceorder $ceNetwork): \App\Entity\CeNetwork
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCeNetwork', [$ceNetwork]);

        return parent::removeCeNetwork($ceNetwork);
    }

}
