<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CeBank extends \App\Entity\CeBank implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'ceBankType', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'ceBankCode', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'ceBankName', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'datec', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'tms', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'fkCeAccount'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'ceBankType', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'ceBankCode', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'ceBankName', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'datec', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'tms', '' . "\0" . 'App\\Entity\\CeBank' . "\0" . 'fkCeAccount'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CeBank $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCeBankType(): ?\App\Entity\ceBankType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCeBankType', []);

        return parent::getCeBankType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCeBankType(?\App\Entity\CeBankType $ceBankType): \App\Entity\CeBank
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCeBankType', [$ceBankType]);

        return parent::setCeBankType($ceBankType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCeBankCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCeBankCode', []);

        return parent::getCeBankCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCeBankCode(string $ceBankCode): \App\Entity\CeBank
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCeBankCode', [$ceBankCode]);

        return parent::setCeBankCode($ceBankCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCeBankName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCeBankName', []);

        return parent::getCeBankName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCeBankName(string $ceBankName): \App\Entity\CeBank
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCeBankName', [$ceBankName]);

        return parent::setCeBankName($ceBankName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatec(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatec', []);

        return parent::getDatec();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatec(\DateTimeInterface $datec): \App\Entity\CeBank
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatec', [$datec]);

        return parent::setDatec($datec);
    }

    /**
     * {@inheritDoc}
     */
    public function getTms(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTms', []);

        return parent::getTms();
    }

    /**
     * {@inheritDoc}
     */
    public function setTms(\DateTimeInterface $tms): \App\Entity\CeBank
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTms', [$tms]);

        return parent::setTms($tms);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkCeAccount(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkCeAccount', []);

        return parent::getFkCeAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function addFkCeAccount(\App\Entity\CeAccount $fkCeAccount): \App\Entity\CeBank
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFkCeAccount', [$fkCeAccount]);

        return parent::addFkCeAccount($fkCeAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFkCeAccount(\App\Entity\CeAccount $fkCeAccount): \App\Entity\CeBank
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFkCeAccount', [$fkCeAccount]);

        return parent::removeFkCeAccount($fkCeAccount);
    }

}
