<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBvFfvio\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBvFfvio/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBvFfvio.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBvFfvio\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBvFfvio\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'BvFfvio',
    'container.build_id' => '94049cb0',
    'container.build_time' => 1536348065,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBvFfvio');
